[package]
name = "permesh-provider-google"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
bytes = "1"
permesh-native-runtime = { path = "../../crates/native-runtime" }
permesh-core.workspace = true
permesh-provider-sdk.workspace = true
permesh-secrets.workspace = true
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
zeroize.workspace = true

[dev-dependencies]
url = "2"
tempfile.workspace = true
permesh-provider-protocol.workspace = true
