[workspace]
resolver = "3"
members = ["providers/github", "providers/google", "providers/cloudflare", "crates/native-runtime", "providers/aws"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.94.1"
license = "MIT"
repository = "https://github.com/NIPE-Solutions/permesh-providers"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "net", "io-util", "io-std", "process", "test-util"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "query"] }
time = { version = "0.3", features = ["formatting", "serde", "parsing"] }
tempfile = "3"
zeroize = { version = "1.8", features = ["serde"] }
permesh-core = { git = "https://github.com/NIPE-Solutions/permesh", rev = "0196197a215c0b244251fe1e3ca1eb759159776b" }
permesh-provider-sdk = { git = "https://github.com/NIPE-Solutions/permesh", rev = "0196197a215c0b244251fe1e3ca1eb759159776b" }
permesh-secrets = { git = "https://github.com/NIPE-Solutions/permesh", rev = "0196197a215c0b244251fe1e3ca1eb759159776b" }
permesh-provider-protocol = { git = "https://github.com/NIPE-Solutions/permesh", rev = "0196197a215c0b244251fe1e3ca1eb759159776b" }

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"
[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
lto = "thin"
strip = true
